<section>

    <div class="review-text">
        <?php /* <p class="p-text">zawartość strony: </p>
          <ul>
          <li><a href="#prace">Remont: opis prac, rzuty, galeria zdjęć domu</li>
          <li><a href="#opis">Stan istniejący: rzuty, opis budynku</li>
          </ul>

          <div  class="prace">
          <a name="prace"/>
          <h4 class="head-title">Remont/przebudowa:</h4>
          <h6 class="aside-title">Rzuty (przewidywany stan po remoncie):</h6>

          <ul>
          <li><a href="/rzut"> parter</a></li>
          <li><a href="/rzut,k,poddasze">poddasze</a></li>
          <li><a href="/rzut,k,przekroj-wschod">przekrój wschodni</a></li>
          <li><a href="/rzut,k,front-poludnie">front południowy</a></li>
          <!-- -->
          <li><a href="/rzut,k,przekroj-zachod">przekrój zachodni</a></li>
          <li><a href="/rzut,k,front-polnoc">front północnego</a>
          </li>
          </ul>

          <p class="p-text">Powierzchnia po remoncie: <?php echo (5.8 + 1.8 + 5 + 9 + 10.5 + 16.85 + 18.96 + 8.5 + 3.5); ?></p>
          <br/><br/>
          </div> */ ?>

        <h6 class="aside-title">Opis budynku:</h6>
        <p class="p-text">
            Jest to budynek parterowy podpiwniczony wybudowany w latach około 1958 - 1960,   z piwnicami tylko pod częścią mieszkalną. Do części mieszkalnej przylega pomieszczenie gospodarcze , 
            <br>które kiedyś było stodołą (około 24m2).</p>

        <ul>
            <li>Piwnice wystają z gruntu na około od 60 do 160cm, </li>
            <li>wysokość piwnic: 210cm, </li>
            <li>wysokość parteru 280cm, </li>
            <li>strych bez ścianki kolankowej, </li>
            <li>kąt nachylenia dachu około 42 stopnie,</li>
            <li>wysokość ścian szczytowych to około 4,28cm.</li>
            <li> Ściany szczytowe domu są na osi wschód-zachód.</li>
            <li> fundamenty(piwnica) są dwuwarstwowe  pierwsza warstwa to układany ciosany kamień na zaprawie cementowej po zewnętrznej części budynku a w środku budynku mieszany pustak(betonowy) z cegłą - nie głębokości ław/fundamentów</li> 
        </ul>

        <p class="p-text">

            <br>
            Dom posiada mury zewnętrzne dwuwarstwowe, warstwa zewnętrzna cegła pełna, wewnątrzna: mieszana pełna cegła, pustak zużlowy/haszowy, grubość całości 42cm.
        </p>

        <p class="p-text">

            Piwnice posiadają 2 rodzaje stropów:</p>

        <ul>
            <li>nad 2 pokojami strop Kleina:<br>
                - wymiary 420x405 - 3 teowniki długości 410cm  ,<br>
                - wymiary 420x456 - 3 teowniki długości 456cm, <br>
                - rozstaw 100cm <br>
                - szerokość teownika 11 cm, wysokość nieznana, grubość około 4-5mm(??), przestrzeń pomiędzy teownikami wypełniona jest cegłą i otynkowana. <br>
                - Nad stropami Kleina znajduje się podłoga na legarach, <br>
                - materiał wypełniający to zaprawa wapienno piaskowa<br>
                - Jedna piwnica do około 1975 r. była stajnią ,  tutaj teownik jest skorodowany<br>
                - druga od około 10lat miała ocieplony od strony piwnicy strop styropianem grubości około 2-3cm. po usuunięciu ocieplenia teownik okazał się mało skorodowany w porównaniu do piwnicy(stajni)
            </li> 
            <li>Teowniki są skorodowane (nie znam grubości skorodowania). </li>
            <li>     
                Reszta stropów jest żelbetowa, pod łazienką są skorodowane pręty około 3m2</li>

        </ul>

        <p class="p-text">
            Pomieszczenie gospodarcze kiedyś było stodołą o wymiarach  320x840cm, to pomieszczenie podzielone jest fundamentem na dwie części.<br>

            w 1. części wysokość 345 x 420 x 320cm  + wysokosć  ścian szczytowych 4.28m <br>
            w 2 część: wysokość 280 x 420 x 320cm  + wysokosć  ścian szczytowych 4.28m <br>

            Pomieszczenie gospodarcze nie ma sufitu tylko  otwartą przestrzeń do poszycia dachowego, brak ściany szczytowej od strony wschodniej części moeszkalnej, brak okna, są tylko drzwi wejściowe szer 90cm x210cm, <br>
            ściana północna kiedyś była drewnianą bramą wejściową, obecnie ten fragment zamurowany jest jednowarstwowym pustakiem haszowym z pozostawionym otworem na drzwi jw. <br>
            Ściany tego pomieszczenia wykonane są z mieszanego materiału są jednowarstwowe z pustaka, pełnej cegły i ubijanego haszu. <br>
            W połowie pomieszczenia wykonany jest fundament wysokości około  ~ 60-80cm ponad grunt.
        </p> 
    
    <h6 class="aside-title">Cel remontu:</h6>
    <ul>
        <li>rozbiórka pomieszczenia gospodarczego</li>
        <li>wymiana dachu - zmniejszenie kubatury strychu, wymiana  więźby dachowej, poszycia</li>
        <li>wymiana stropu nad parterem z drewnianego na drewniany</li>
        <li>z połowy parteru wydzielić:
            <ol>    
                <li>drugą sypialnię</li>
                <li>WC</li>
            </ol> 

        </li>
        <li>
            wykorzystać wysokie fundamenty pomieszczenia gospodarczego na:
            <ol>
                <li>nowy hall/wejście</li>
            </ol>
        </li>
        <li>ocieplone ściany</li>
        <li> piwnice izolowane przeciwwilgociowo</li>
        
    </ul>
    
        <a href="/rzut">więcej szczegółów na rysunkach projektowych</a>
    <br/><br/>
    <h6 class="aside-title">Prace do wykonania:</h6>
    <ul>
        
          <li>WYBURZENIA<br><br>
            - Rozbiórka ściany szczytowej zachodniej<br>
            -Rozbiórka północnego ganku blaszanego<br>
            -Rozbiórka pomieszczenia gospodarczego ~24m2,  pozostałyby tylko fundamenty, <br>
            -Rozbiórka kominów, <br>
            -Rozbiórka śianek działowych nad stropem żelbetowym na rzecz ścianek z regipsów<br>
            -Wyburzenie otworu drzwiowego 200x90cm w ścianie zewnętrznej wschodniej parteru, będzie to wejście z holu do pokoju,<br>
            -Wyburzenie otworu drzwiowego 200x110cm w ścianie nośnej wewnętrznej, będzie to wejście z salonu do kuchni,<br>
            -Pogłębienie w dół otworu okiennego na balkonowe w salonie  z 160x160 na 160x230</li>

        </li> 
        
        <li>
            Zmniejszenie kubatury/wysokości strychu,<br><br>
            -dach o nowym kącie nachylenia 35stopni(obecny ~42),  <br>
            -wysokość strychu zamiast obecnej 428cm będzie 330cm, <br>

            Jeśli byłoby to możliwe ekonomicznie i korzytne konstrukcyjnie (odciążenie ścian) to wymienić dach dwuspadowy na czterospadowy<br>
</li>
        <li> Nowy(lub wzmocniony) strop drewniany nad parterem  i nowa więźba dachowa, pokrycie dachowe blacha trapezowa 'aluminiowa':
            <br><br>

        <li>Wzmocnienie/wyrównanie fundamentów pod izolacje</li>

        
        <li>PRZEBUDOWA POMIESZCZENIA GOSPODARCZEGO NA HAL<br>    
            Na pozostałym po stodole podniesionym fundamencie  budowa: hal(~310x280) i balkon/minitaras (~350x120) =  480x350<br><br>
            Ściany pustak porotherm, sufit powieszany, daszek spadek pomiędzy 280cm a 210cm wysokości parteru w halu, <br>
            daszek dwuspadowy na osi północ-południe,                                        

        </li> 
        <li> Ocieplenie murów domu i izolacja przeciwwilgociowa fundamentów domu  wraz z posadzką (obecnie brak ocieplenia poziomego piwnic i izolacji przeciwwilgociowej )</li>
        <li>Nowe wywietrzniki,komin</li>

        <?php /*

          <li>prace na strychu: ścianki kolankowe ocieplone, sufit podwieszany ocieplony, okna połaciowe 4x 78x140  na stronie południowej,wschodniej i zachodniej, ocieplenie stropu nad parterem, ofasowania kominów, dobudowa nowych wywietrzników<br>
          </li>


          <li>  Wzmocnie stropów Klein'a:
          <br>  <br>
          Wzmocnienie samych teowników od dołu, od góry: usunięcie  podłogi, resztek starego wypełnienia, wysypanie kuleczek keramzytowych, <br>
          nowe legary co 50cm + podłoga  legary będą gęściej niż jest to obecnie (podłoga się ugina, legary są co 1m wzdłuż teowników położone)  - lepsza byłaby wylewka jeśli jest taka możliwość ??<br>
          </li>
          <li>Wzmocnienie stropu żelbetowego o powierzchni 3.5m2</li>
         * */ ?>



    </ul>

<a href="/rzut">więcej szczegółów na rysunkach</a>
    <?php /* <h4 class="aside-title">Galeria zdjęć:</h4>   

      <p class="p-text">W  <a href="/galeria">galerii </a> zdjęcia więźby dachowej , fragmenty stropu Kleina, pogłądowy rysunek ewentualnie nowego kształtu dachu.</p>

     */ ?>
</div>
   
        

</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.switcher.dom.js"></script>
<script type="text/javascript">
    // <![CDATA[
    // 
    // 
    //var canv = jQuery('#canvas');

    //console.log(canv);
    //
    mig.switcher.dom(window, {
    });
    // ]]>
</script>
<?php $this->clean(); ?>