<svg  version="1.1"
         baseProfile="full"
         accesskey=""
        class="svg-canvas"
         viewBox="0 0 968 945"
         width="968" 
         height="945">
<?php $this->render('projection/view/partial/style.phtml'); ?>
  
  <rect  x="0" y="0" width="968" height="945" fill="#ccc" stroke="black"/>
  <rect  x="42" y="42" width="884" height="861" fill="#fff" stroke="black"/>  
   
 <rect  x="162" y="162" width="644" height="621" fill="#fff" stroke="black"/>
 <rect  x="192" y="192" width="584" height="561" fill="#fff" stroke="black"/>
 
 <text x="470" y="180">584x561=32.5m2</text>
 <text x="170" y="180">h:135-ścianki kolankowe</text>
   
     <text x="50" y="72">strop drewniany</text>
    
     <rect x="355" y="370" width="90" height="90" fill="#fffccc" stroke="black"></rect>
     <text x="365" y="390">schody strych</text>
     
     <rect id="komin" y="490" x="475" width="16" height="22" fill="#ccc" stroke="black"></rect>
     
   
     <text x="605" y="690">ocieplany strych</text>
     
    <text x="475" y="485">komin</text> 
     <g class="wywierzniki">
        <rect stroke="black" fill="yellow" height="40" width="40" x="560" y="260"></rect>
       <text x="562" y="280">piec co</text> 

       <rect stroke="black" fill="yellow" height="20" width="20" x="671" y="200"></rect>
        <text x="672" y="215">02</text>
        
        
        <rect stroke="black" fill="yellow" height="15" width="15" x="158" y="285"></rect>
        <text x="160" y="305">WC,O2</text>
        
        <rect stroke="black" fill="yellow" height="15" width="15" x="458" y="42"></rect>
    </g>
</svg>