<section>
    <?php $this->render('projection/view/partial/tools.phtml'); ?> 
    
    
    
    
    
    <svg  version="1.1"
          baseProfile="full"
          accesskey=""
          class="svg-canvas"
          viewBox="0 0 1320 945"
          width="1320" 
          height="945">
          <?php $this->render('projection/view/partial/style.phtml'); ?>

    <rect  x="0" y="0" width="1320" height="945" fill="#ccc" stroke="black"/>
    <rect  x="42" y="42" width="1236" height="861" fill="#fff" stroke="black"/>

    <rect  x="968" y="0" width="350" height="462" fill="red" stroke="black" style="opacity: 0.2"/>

    <!-- schody -->
    <rect  x="42" y="142" width="112" height="198" fill="#fffccc" stroke="black"/>
    
    
    <rect stroke="black" fill="yellow" height="40" width="40" x="560" y="260"></rect>
    
    <rect  x="150" y="142" width="10" height="320" fill="#ccc" stroke="black"/>
    <rect  x="42" y="142" width="118" height="10" fill="#ccc" stroke="black"/>
     <rect  x="42" y="285" width="118" height="10" fill="#ccc" stroke="black"/>
    <rect  x="968" y="462" width="350" height="42" fill="#ccc" stroke="black"/>
    <rect  x="968" y="782" width="350" height="42" fill="#ccc" stroke="black"/>
<rect  x="970" y="826" width="350" height="120" fill="grey" stroke="black"/>
    <rect  x="160" y="285" width="80" height="8" fill="#ccc" stroke="black"/>
    
    <rect x="348" y="0" width="55" height="42" fill="#fcfcfc" stroke="black"></rect>

    <!-- sciany nosne -->

    <rect  x="42" y="462" width="884" height="28" fill="#ccc" stroke="black"/> <!-- nosna -->
    <rect  x="446" y="489" width="28" height="416" fill="#ccc" stroke="black"/><!-- nosna ?  salon -->

    <!-- kominy -->
    <rect  y="490" x="475" width="16" height="22" fill="#ccc" stroke="black"/>
    
    <rect y="42" x="446" width="12" height="274" fill="#ccc" stroke="black"></rect>
<rect y="348" x="865" width="60" height="4" fill="#ccc" stroke="black"></rect>

<rect x="500" y="462" width="90" height="28" fill="#fcfcfc" stroke="black"></rect>

    <g id="meble-kuchnia" class="meble">
    <rect  y="104" x="864" width="60" height="40" fill="white" stroke="black"/>
    <rect  y="80" x="685" width="60" height="240" fill="white" stroke="black"/>
  <rect  y="42" x="685" width="238" height="60" fill="white" stroke="black"/>
  <rect  y="145" x="864" width="60" height="200" fill="white" stroke="black"/>
  
    
    <rect  y="42" x="740" width="80" height="60" fill="#81DAF5" stroke="black"/>
    <rect  y="355" x="874" width="50" height="100" fill="white" stroke="black"/>
    
    <rect  y="182" x="690" width="60" height="60" fill="white" stroke="black"/>  <!---->


    </g>

    <g id="meble-sypialnia-mala" class="meble">
    <rect  y="45" x="343"  width="100" height="210" fill="white" stroke="black"/>
    <rect y="42" x="42"  width="60" height="100" fill="white" stroke="black"/>
    
    
    <rect  y="275" x="364"  width="80" height="28" fill="white" stroke="black"/>
    
    <rect  y="45" x="270" width="70" height="40" fill="white" stroke="black"/>
    <rect  y="200" x="170" width="60" height="80" fill="white" stroke="black"/>     
    </g>

    <g id="meble-sypialnia-duza" class="meble">
    <rect  y="490" x="46" width="60" height="120" fill="white" stroke="black"/>
    <rect  y="520" x="130" width="60" height="50" fill="white" stroke="black"/>

    <rect  y="615" x="70" width="240" height="50" fill="white" stroke="black"/>
    <rect  y="665" x="120" width="145" height="165" fill="white" stroke="black"/>
    <rect  y="650" x="385" width="60" height="240" fill="white" stroke="black"/> 
    <rect  y="550" x="395" width="50" height="80" fill="white" stroke="black"/>
    </g>




    <rect class="meble" id="dywan-salon" y="620" x="539" width="300" height="200" fill="white" stroke="black"/>
    <g id="meble-salon" class="meble">
    <rect y="494" x="505"  width="160" height="40" fill="white" stroke="black"/>
    <rect  y="740" x="477" width="47" height="130" fill="white" stroke="black"/>

    <rect y="670" x="838"  width="85" height="195" fill="white" stroke="black"/>
    <rect  y="500" x="863" width="60" height="60" fill="white" stroke="black"/>

    <rect  y="670" x="560" width="215" height="87" fill="white" stroke="black"/>
    <rect  y="670" x="560" width="165" height="87" fill="white" stroke="black"/>

    <rect  y="600" x="630" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="600" x="720" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="600" x="580" width="45" height="50" fill="white" stroke="black"/>

    <rect  y="680" x="500" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="680" x="785" width="45" height="50" fill="white" stroke="black"/>

    <rect  y="790" x="720" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="790" x="630" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="790" x="580" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="564" x="475" width="60" height="90" fill="white" stroke="black"/>
    </g>

    <g id="meble-hol" class="meble">
    
    <rect  y="505" x="1150" width="120" height="60" fill="white" stroke="black"/>

    <rect  y="600" x="1210" width="60" height="140" fill="white" stroke="black"/>
    <rect  y="682" x="985" width="60" height="60" fill="white" stroke="black"/>

    <rect  y="630" x="1130" width="50" height="80" fill="white" stroke="black"/>

    </g>

    <g id="meble-taras" class="meble">
    <rect  y="845" x="1125" width="50" height="50" fill="white" stroke="black"/>

    <rect  y="845" x="1195" width="60" height="60" fill="white" stroke="black"/>
    <rect  y="845" x="990" width="60" height="60" fill="white" stroke="black"/>

    </g>
    
    <g id="wc" class="meble">
     <rect  y="300" x="165" width="40" height="65" fill="#81DAF5" stroke="black"/>
     <rect  y="330" x="225" width="20" height="40" fill="#81DAF5" stroke="black"/>
    </g>


    <g id="lazienka" class="meble">
    <rect  y="220" x="460" width="90" height="90" fill="#81DAF5" stroke="black"/>
    <rect  y="52" x="462" width="65" height="40" fill="#81DAF5" stroke="black"/>
    <!--  
  
   <rect  y="196" x="460" width="40" height="100" fill="#fff" stroke="black"/>
    -->
    
    <!---->
    <rect  y="200" x="630" width="38" height="20" fill="#fff" stroke="black"/>
    <rect  y="100" x="460" width="40" height="110" fill="#fff" stroke="black"/>
     <rect  y="126" x="460" width="40" height="60" fill="#81DAF5" stroke="black"/>
     
    <polygon class="wanna" points="577,45 663,45 663,195 633,195" fill="#81DAF5" stroke="black"/>
    </g>
   






    <!-- sciany dzialowe -->
  <!--  <rect  y="334" x="250" width="110" height="8" fill="#ccc" stroke="black"/> dzialowa sien  
    <rect  y="192" x="338" width="50" height="8" fill="#ccc" stroke="black"/>
    <rect  y="42" x="338" width="8" height="150" fill="#ccc" stroke="black"/>--> 




    <rect  y="285" x="240" width="8" height="176" fill="#ccc" stroke="black"/><!-- dzialowa spizarka -->

    <rect  y="42" x="674" width="8" height="278" fill="#ccc" stroke="black"/><!-- dzialowa lazienka -->

    <rect  y="42" x="926" width="42" height="861" fill="#ccc" stroke="black"/><!-- dzialowa kuchnia -->

    <rect  y="308" x="243" width="430" height="12" fill="#ccc" stroke="black"/><!-- dzialowa przedpokoj -->

    <!-- okna -->
    <rect  x="127" y="0" width="96" height="42" fill="#ffccff" stroke="black"/><!-- okno sien -->
    <rect  x="127" y="0" width="16" height="42" fill="#f5f5f5" stroke="black"/>

    

    <rect  x="471" y="0" width="55" height="42" fill="#ffccff" stroke="black"/><!-- okno lazienka -->
  
    <rect  x="699" y="0" width="122" height="42" fill="#ffccff" stroke="black"/><!-- okno kuchnia -->
  
   
    
    <rect  x="1035" y="462" width="95" height="42" fill="#ffccff" stroke="black"/><!-- drzwi stodola -->
    <rect  x="1030" y="270" width="105" height="190" fill="#cccfff" stroke="black"/>
    <rect  x="1075" y="782" width="120" height="42" fill="#ffccff" stroke="black"/>

<rect x="355" y="370" width="90" height="90" fill="#fffccc" stroke="black"></rect>
<rect x="440" y="405" width="260" height="55" fill="#fffccc" stroke="black"></rect>

    <rect  x="178" y="903" width="165" height="42" fill="#ffccff" stroke="black"/><!-- okno salon -->

    <rect  x="639" y="903" width="165" height="42" fill="#ffccff" stroke="black"/><!-- okno sypialnia -->
    
    <rect stroke="black" fill="yellow" height="20" width="20" x="671" y="200"></rect>

<rect stroke="black" fill="yellow" height="15" width="15" x="458" y="42"></rect>

    <!-- drzwi -->
    <rect  x="150" y="378" width="10" height="80" fill="#ffcccc" stroke="black"/><!-- drzwi sien -->
    <rect  x="240" y="378" width="8" height="80" fill="#ffcccc" stroke="black"/><!-- drzwi sien -->
    <!-- <rect  x="333.5" y="303" width="85" height="12" fill="#ffcccc" stroke="black"/>drzwi spizarka -->
    <rect  x="260" y="308" width="80" height="12" fill="#ffcccc" stroke="black"/><!-- drzwi lazienka -->
    <rect  x="600" y="308" width="70" height="12" fill="#ffcccc" stroke="black"/><!-- drzwi kuchnia -->

    <rect  x="280" y="462" width="88" height="28" fill="#ffcccc" stroke="black"/><!-- drzwi salon -->
    <rect  x="730" y="462" width="110" height="28" fill="red" stroke="black"/><!-- drzwi sypialnia -->

    <rect  x="926" y="565" width="42" height="90" fill="red" stroke="black"/><!-- drzwi sypialnia --> 



    <g id="grzejniki" class="co-inst">
    <rect id="grzejnik-salon" y="880" x="530" width="70" height="15" fill="orange" stroke="black"/>
    <rect id="grzejnik-salon-2" y="880" x="840" width="70" height="15" fill="orange" stroke="black"/>
    <rect id="grzejnik-salon-3" y="840" x="590" width="240" height="30" fill="orange" stroke="black" style="opacity:0.3"/>
    
    
    
    <rect id="grzejnik-hal" y="510" x="975" width="50" height="15" fill="orange" stroke="black"/>
    <rect id="grzejnik-hal-2" y="760" x="1220" width="50" height="15" fill="orange" stroke="black"/>
    <rect id="grzejnik-hal-3" y="730" x="1040" width="160" height="30" fill="orange" stroke="black"  style="opacity:0.3"/>
    <rect id="grzejnik-kuchnia" y="145" x="785" width="30" height="150" fill="orange" stroke="black"  style="opacity:0.3"/>
    <rect id="grzejnik-sypialnia-duza" y="880" x="205" width="110" height="15" fill="orange" stroke="black"/>
    <rect id="grzejnik-przedpokoj" y="438" x="530" width="110" height="15" fill="orange" stroke="black"/>

    <rect id="grzejnik-wc" y="296" x="225" width="10" height="30" fill="orange" stroke="black"/>

    <rect id="grzejnik-sypialnia-mala" y="70" x="110" width="150" height="30" fill="orange" stroke="black"  style="opacity:0.3"/>
    <rect id="grzejnik-lazienka" y="47" x="543" width="30" height="10" fill="orange" stroke="black"/>
    <rect id="grzejnik-lazienka-2" y="244" x="566" width="30" height="10" fill="orange" stroke="black"/>
    </g>

    <g id="instalacja-co"  class="co-inst">
    <polygon points="317,890  928,890"  stroke="orange" stroke-width="4"/>    
    <polygon points="928,890  927,776"  stroke="orange" stroke-width="4"/>
    <polygon points="927,776  1224,771"  stroke="orange" stroke-width="4"/>    
    <polygon points="927,776   927,445"  stroke="orange" stroke-width="4"/> 
    <polygon points="927,450 643,450"  stroke="orange" stroke-width="4"/>    
      <polygon points="929,515 978,515"  stroke="orange" stroke-width="4"/>
    <polygon points="239,304 578,304"  stroke="orange" stroke-width="4"/>
    <polygon points="260,48 547,48"  stroke="orange" stroke-width="4"/>
    <polygon points="596,252 788,252"  stroke="orange" stroke-width="4"/>    
    <polygon points="446,50 446,308"  stroke="orange" stroke-width="4"/>
     <polygon points="578,306 578,438"  stroke="orange" stroke-width="4"/>
    </g>

  <g id="instalacja-h20-zimna" class="inst">    
    <polygon points="199,326 578,326" stroke="blue" stroke-width="4"/>
    <polygon points="452,88 452,320" stroke="blue" stroke-width="4"/>
    <polygon points="450,88 742,88" stroke="blue" stroke-width="4"/>    
    </g>
    
    <g id="instalacja-h20-ciepla" class="inst">    
    <polygon points="239,314 578,314" stroke="red" stroke-width="4"/>
    <polygon points="461,150 458,314" stroke="red" stroke-width="4"/>
    <polygon points="668,94 742,94" stroke="red" stroke-width="4"/> 
    <polygon points="668,94 668,257" stroke="red" stroke-width="4"/>
    <polygon points="668,257 584,257" stroke="red" stroke-width="4"/>
    </g>
    
   

    <g id="instalacja-kanalizacja" class="inst">
    <polygon points="199,333 466,333"  stroke="#8A0829" stroke-width="6"/>
     <polygon points="466,333 466,80"  stroke="#8A0829" stroke-width="6"/>
     <polygon points="466,80 745,80"  stroke="#8A0829" stroke-width="6"/>
    </g>

   <!-- <g id="instalacja-elektyka">

        <g id="elektryka-sypialnia">
                <polygon points="929,464 928,397"  stroke="#0B610B" stroke-width="2"/>
                <polygon points="687,461 929,464"  stroke="#0B610B" stroke-width="2"/>
                <polygon points="687,44 687,461"  stroke="#0B610B" stroke-width="2"/>
                <polygon points="690,220 800,220"  stroke="#0B610B" stroke-width="2"/>
                <polygon points="357,35 687,35"  stroke="#0B610B" stroke-width="2"/>
                <circle cx="686" cy="334" r="4" stroke="#0B610B" stroke-width="1" fill="#0B610B"  data-alt="wyĹ‚Ä…cznik"/>
                <circle cx="800" cy="220" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
                <rect y="397" x="926" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
                <rect y="200" x="684" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
        </g>
        
        <g id="elektryka-kuchnia">
             <rect x="662" y="90" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             <rect x="350" y="65" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             
             <rect x="552" y="44" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             <rect x="670" y="322" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             <circle cx="510" cy="220" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
             <circle cx="394" cy="340" r="4" stroke="#0B610B" stroke-width="1" fill="#0B610B" />
              <polygon points="393,220 500,220"  stroke="#0B610B" stroke-width="2"/>
              <polygon points="393,220 393,340"  stroke="#0B610B" stroke-width="2"/>
              <polygon points="357,35 357,141"  stroke="#0B610B" stroke-width="2"/>
        </g>
        
        <g id="elektryka-wc">
        <circle cx="198" cy="355" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
        <circle cx="235" cy="360" r="4" stroke="#0B610B" stroke-width="1" fill="#0B610B" />
        <rect x="232" y="345" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
        </g>
        
        <g id="elektryka-schody">
        <circle cx="96" cy="450" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
        <circle cx="145" cy="360" r="4" stroke="#0B610B" stroke-width="1" fill="#0B610B" />
        <rect x="142" y="345" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
        <polygon points="96,344 393,344"  stroke="#0B610B" stroke-width="2"/>
        <polygon points="96,344 96,441"  stroke="#0B610B" stroke-width="2"/>
        </g>
        
        <g id="elektryka-lazienka">
             <rect x="333" y="36" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             
             <circle cx="373" cy="49" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
             <circle cx="222" cy="135" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
             
              <polygon points="235,137 339,137"  stroke="#0B610B" stroke-width="2"/>
             </g>
    </g>-->
    <!-- teksty -->


    <!-- tekst sien -->
     <text x="46" y="225" class="meble">pawlacz-skos</text>
    <text x="46" y="265">110x140</text>
    <text x="46" y="335">110x305=3.5</text>
    <text x="46" y="320">schody piwnica</text>
    <text x="46" y="385">110x120=1.3</text>   
    <text x="166" y="400">WC 1.4</text>
    <text x="166" y="420">170x80</text>
    
    

    

    <!-- tekst lazienka --> 
    <text x="475" y="30">w:55x150</text>
    <text x="530" y="133">łazienka</text>
    <text x="465" y="240" class="meble">brodzik 90x90</text>
    <text x="540" y="110" class="meble">wanna 85x150</text>
   <text x="505" y="153">210x260=5.5</text>
   <text x="562" y="280">piec co</text>
   <text x="672" y="215">02</text>

    <!-- tekst kuchnia --> 
    <text x="705" y="35">w:120x150</text>
     <text x="770" y="160">kuchnia</text>
    <text x="770" y="180">240x270=6.5</text>
    <text x="700" y="220" class="meble">piec induk. 60x60</text>
    <text x="717" y="70" class="meble">zlew 80x60</text>
    
    
    <!-- tekst sypialnia mala --> 
    <text x="140" y="30">w:80x210</text>
    <text x="190" y="100">sypialnia 8.2m2</text>
    <text x="190" y="120">280x240=6.7</text>
    <text x="190" y="140">115x100=1.1</text> 
    <text x="190" y="160">200x20=0.4</text> 
      <text x="190" y="180">~400x260=10.5</text> 
     

    <!-- tekst przedpokoj --> 
    <text x="280" y="360">przedpokój  140x680=9.52</text>
    <text x="535" y="430">schody strych</text>

    <!-- tekst salon --> 
    <text x="225" y="930">w:162x160</text>
    <text x="190" y="850">sypialnia</text>
    <text x="190" y="870">405x416=16.85</text>
    <text x="300" y="482">w:88</text>

    <!-- tekst sypialnia -->    
    <text x="685" y="940">w:162x230</text>
    <text x="650" y="870">salon</text>
    <text x="650" y="890">456x416=18.96</text>    
    <text x="735" y="482">w:110x210</text>


    <text x="1055" y="425">schody</text> 
    <text x="1055" y="485">w:95x200</text>
    <text x="1095" y="805">w:120x200</text>
    <text x="925" y="635">w:90x210</text>
    
    
    <text x="1055" y="585">hol 310 x 275 =8.5 </text>

    <text x="1105" y="925">taras 3.5 x 1.20 = 4.2</text>

   
 
    
    
    
    
    
    
    <text x="480" y="70" class="meble">wc</text>
<text x="175" y="330" class="meble">wc</text>

    <g class="wywierzniki">
   

    <rect stroke="black" fill="yellow" height="15" width="15" x="158" y="285"/>
    <text x="160" y="305">WC,O2</text> 

    
   
    </g>
    </svg>     
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
<script type="text/javascript">
    // <![CDATA[

    mig.canvas.view(window, {});
    
    jQuery('.switch-off-furniture').click(function(){
        
    });
    // ]]>
</script>
<?php $this->clean(); ?>
    